// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getAvatar = `-- name: GetAvatar :one
SELECT user_id, hat_id, shirt_id, jacket_id, bottoms_id, shoes_id FROM avatars WHERE user_id = $1
`

// ユーザーの現在のアバター状態を取得
func (q *Queries) GetAvatar(ctx context.Context, userID int64) (Avatar, error) {
	row := q.db.QueryRowContext(ctx, getAvatar, userID)
	var i Avatar
	err := row.Scan(
		&i.UserID,
		&i.HatID,
		&i.ShirtID,
		&i.JacketID,
		&i.BottomsID,
		&i.ShoesID,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :many
SELECT item_id FROM user_items WHERE user_id = $1
`

// インベントリ（所持アイテム一覧）の取得
func (q *Queries) GetInventory(ctx context.Context, userID int64) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getInventory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var item_id int32
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one
SELECT id, name, category, image_url FROM items WHERE id = $1
`

// アイテム詳細の取得
func (q *Queries) GetItem(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.ImageUrl,
	)
	return i, err
}

const saveAvatar = `-- name: SaveAvatar :exec
INSERT INTO avatars (
    user_id, hat_id, shirt_id, jacket_id, bottoms_id, shoes_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (user_id) DO UPDATE SET
    hat_id = EXCLUDED.hat_id,
    shirt_id = EXCLUDED.shirt_id,
    jacket_id = EXCLUDED.jacket_id,
    bottoms_id = EXCLUDED.bottoms_id,
    shoes_id = EXCLUDED.shoes_id
`

type SaveAvatarParams struct {
	UserID    int64
	HatID     sql.NullInt32
	ShirtID   sql.NullInt32
	JacketID  sql.NullInt32
	BottomsID sql.NullInt32
	ShoesID   sql.NullInt32
}

// アバター状態の保存（着せ替え）
func (q *Queries) SaveAvatar(ctx context.Context, arg SaveAvatarParams) error {
	_, err := q.db.ExecContext(ctx, saveAvatar,
		arg.UserID,
		arg.HatID,
		arg.ShirtID,
		arg.JacketID,
		arg.BottomsID,
		arg.ShoesID,
	)
	return err
}
